# fly.toml app configuration file generated for friendly-reminder-bot on 2023-09-22T09:21:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "friendly-reminder-bot"
primary_region = "ams"

[build]
start = "node /app/build/index.js"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 0
processes = ["app"]
